- name: moodulos del sistema
  become: true
  hosts: curso01
  tasks:
    - name: Usar java 9
      alternatives: 
        name: java
        path: /usr/lib/jvm/java-1.16.0-openjdk-amd64/

    - name: Añadir clave ansible usuario root
      authorized_key:
        user: root
        key: "ssh-rsa fsdfDFEefdELSGFK43== example@example.com"

    - name: Crear programacion copia seguridad
      cron:
        name: "crear backup"
        hour: 2
        minute: 0
        job: "/root/scripts/backup.sh"

    - name: Crear programacion copia seguridad
      cron:
        name: "crear backup"
        hour: 2
        minute: 0
        job: "/root/scripts/backup.sh"
        cron_file: crear_backup
        user: root

    - name: Crear s.ficheros xfs
      filesystem:
        dev: /dev/vda2
        fstype: xfs
      ignore_errors: true

    - name: Habilitar http/https
      firewalld:
        state: enabled
        zone: public
        service: "{{ item }}"
        permanent: true
        immediate: true
      delegate_to: curso04
      with_items:
        - "http"
        - "https"
      
    - group:
        name: jboss
        state: present
        gid: 185

    - debug:
        var: ansible_hostname

    - hostname:
        name: ubuntu.oforte.net

    - ping:

    - setup:

    - debug:
        var: ansible_hostname

    - timezone:
        name: "Europe/Madrid"

    - debug:
        var: ansible_fqdn