# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :ssh_username => "ubuntuuser",
        :ssh_password => "ubuntuuser123",
        :ssh_insert_key => false,
        :name => "server1",
        :box => "generic/ubuntu2010",
        :eth1 => "192.168.0.251",
        :mem => "512",
        :cpu => "1"
    },
    {
        :ssh_username => "centosuser",
        :ssh_password => "centosuser123",
        :ssh_insert_key => false,
        :name => "server2",
        :box => "centos/7",
        :eth1 => "192.168.0.252",
        :mem => "512",
        :cpu => "1"
    },
    {
        :ssh_username => "debianuser",
        :ssh_password => "debianuser123",
        :ssh_insert_key => false,
        :name => "server3",
        :box => "generic/debian10",
        :eth1 => "192.168.0.253",
        :mem => "512",
        :cpu => "1"
    }
]

Vagrant.configure("2") do |config|
  
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      
      config.vm.hostname = opts[:name]

      # config.ssh.username = opts[:ssh_username]
      # config.ssh.password = opts[:ssh_password]
      # config.ssh.insert_key = opts[:ssh_insert_key]

      config.vm.provision "shell",
      env: {"MYPASS" => opts[:ssh_password], "MYUSER" => opts[:ssh_username]},
      inline: <<-SHELL
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
        systemctl restart sshd.service

        useradd -m -s /usr/bin/bash $MYUSER
        echo -e "$MYPASS\n$MYPASS" | passwd $MYUSER

        usermod -aG sudo $MYUSER

        echo "$MYUSER    ALL=(ALL)       ALL" > /etc/sudoers
      SHELL

      config.vm.box = opts[:box]
      
        config.vm.network "public_network", ip: opts[:eth1],
        :dev => "xenbr0",
        :mode => "bridge",
        :type => "bridge"      
        
        config.vm.provider :libvirt do |libvirt|
          libvirt.cpus = opts[:cpu]
          libvirt.memory = opts[:mem]

        end
    end
  end
end