- name: Trabajar con modulos packaging
  hosts: curso03:curso01
  become: true
  tasks:
    
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/google-chrome.list
        state: absent

    - name: Actualizar lista de paquetes
      apt:
        update_cache: yes
    
    - name: Actualizar paquetes
      apt:
        upgrade: dist
    
    - name: Instalar nginx
      apt:
        name: nginx
        state: latest
        
    - name: Añadir clave apt
      apt_key:
        url: "https://ftp-master.debian.org/keys/archive-key-6.0.asc"
        state: present

    - name: Add specified repository into sources list using specified filename
      apt_repository:
        repo: deb http://deb.debian.org/debian buster-backports main contrib non-free
        state: present
        filename: google-chrome
      when: ansible_distribution == '{{ distri }}'