- name: Instala AWX en Ubuntu
  hosts: localhost
  become: True
  tasks:
    - name: Actualiza los repositorios
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Add an Apt signing key, uses whichever key is at the URL
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add specified repository into sources list
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu\
 {{ ansible_distribution_release }} stable
        state: present

    - name: Actualiza los repositorios e instala docker.
      apt:
        name: docker-ce docker-ce-cli containerd.io ansible nodejs npm python3-pip git pwgen
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Add the user to docker group
      ansible.builtin.user:
        name: {{ ansible_user_id }}
        group: docker

    - name: Restart docker
      ansible.builtin.systemd:
        name: docker.service
        state: reloaded

    - name: This command will change the working directory to somedir/
      ansible.builtin.shell:
        cmd: curl -s https://api.github.com/repos/docker/compose/releases/latest | grep browser_download_url | grep docker-compose-Linux-x86_64 | cut -d '"' -f 4 | wget -qi -

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: {{ lookup('env', 'PWD') }}/docker-compose-Linux-x86_64
        owner: foo
        group: foo
        mode: u+x

    - name: Comprobar que fichero {{ lookup('env', 'PWD') }}/docker-compose-Linux-x86_64 existe
      stat: 
        path: {{ lookup('env', 'PWD') }}/docker-compose-Linux-x86_64
      register: dc_stat

    - name: Mover docker compose a PATH
      command: mv $PWD/docker-compose-Linux-x86_64 /usr/local/bin/docker-compose
      when: dc_stat.stat.exists

    - name: Instala "npm" node.js package globally.
      community.general.npm:
        name: npm
        global: yes

  - name: Obtener versi贸n docker-compose
    shell:
      cmd: docker-compose --version | cut -d" " -f3 | sed 's/,//' | tr -d '\n'
    register: dcv

  - debug: 
      msg: 
        - La versi贸n de docker-compose es {{ dcv.stdout }}

  - name: Instalar docker-compose version {{ dcv.stdout }}
    pip:
      name: docker-compose=={{ dcv.stdout }}
      executable: pip3

  - name: Obtener versi贸n y archivo zip a su vez
    ansible.builtin.shell:
      cmd: curl -s https://api.github.com/repos/ansible/awx/releases/latest | grep zipball_url | grep awx | cut -d '"' -f 4 | cut -d"/" -f8 | tr -d "\n"
    register: aav

  - debug: 
      msg: 
        - La versi贸n de ansible AWX es {{ aav.stdout }} 

  - name: Descargar archivo awx
    ansible.builtin.shell:
      cmd: curl -s https://api.github.com/repos/ansible/awx/releases/latest | grep zipball_url | grep awx | cut -d '"' -f 4 | wget -qi -