- name: Primer play
  hosts: curso01
  become: True
  tasks:
    - name: Instalar vim
      apt: name=vim state=latest
    - include: instalar_apache2.yml

- name: Segundo play
  include: segundo_play.yml


