- name: Instalar httpd
  include: instalar-httpd.yml


# - name: Instalar apache2
#   apt: name=apache2 state=latest
#   when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# - name: Instalar httpd
#   yum: name=httpd state=latest
#   when: ansible_distribution == "CentOS"

# - name: Iniciar y habilitar servicio
#   service: name=apache2 state=started enabled=true
#   when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

# - name: Iniciar y habilitar servicio
#   service: name=httpd state=started enabled=true
#   when: ansible_distribution == "CentOS"

# - name: Copiar fichero de configuracion
#   copy: src=apache2.conf dest=/etc/apache2/apache2.conf
#   notify: restart_httpd

# - name: Copiar fichero index.html
#   template: src=index.html.j2 dest=/var/www/html/index.html