- name: Ejemplos de modulos de ficheros y openssl
  hosts: curso03
  become: True
  tasks:

    - name: Crear fichero con contenido especificado
      copy:
        content: Esto es un ejemplo 4
        dest: /tmp/ejemplo_file
        backup: yes

    - name: Propiedades fichero
      file: 
        path: /tmp/ejemplo_file
        backup: yes
        state: absent

    - name: Visualizar backups realizados al modificar el contenido del archivo 2
      command: ls -la /tmp/
      register: visualizar2

    - debug:
        var: visualizar2.stdout_lines
        
    - name: Visualizar backups realizados al modificar el contenido del archivo
      command: ls -la /tmp/ejemplo_file
      register: visualizar
      ignore_errors: True

    - debug:
        var: visualizar.stderr_lines


