# https://gist.github.com/ihassin/8106956
- hosts: curso01
  # user: vagrant
  become: true
  vars_files:
    - vars.yml

  tasks:

    - name: Update repositories cache and install "foo" package
      apt:
        update_cache: yes

    - name: Upgrade the OS (apt-get dist-upgrade)
      apt:
        upgrade: dist

    - name: Install MySQL
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - mysql-server
        - mysql-client
        - python3-pip
        - python3
        - python-setuptools
      
    - name: Copy .my.cnf file with root password credentials
      # template: src=templates/.my.cnf dest=/etc/mysql/my.cnf owner=root mode=0600
      template: src=templates/.my.cnf dest=/root/.my.cnf owner=root mode=0600

    - name: Install pip
      pip:
        name: ["PyMySQL"]

    - name: Start the MySQL service
      action: service name=mysql state=started

    # - name: Remove the test database
    #   mysql_db: name=test state=absent

    - name: Create deploy user for mysql
      mysql_user: user="deploy" host="%" password={{mysql_root_password}} priv=*.*:ALL,GRANT

    - name: Ensure anonymous users are not in the database
      mysql_user: user='' host=$item state=absent
      with_items:
        - 127.0.0.1
        - ::1
        - localhost


    - name: Update mysql root password for all root accounts
      mysql_user: name=root host={{item}} password={{mysql_root_password}}
      with_items:
        - 127.0.0.1
        - ::1
        - localhost