- name: Crear fichero usando variables
  hosts: curso01
  # hosts: localhost
  # connection: local
  vars:
    - miip: "1.2.3.4"
  tasks:
    - name: Crear fichero hosts
      template: src=hosts.j2 dest=/tmp/hosts

    - name: Ver archivo template
      command: cat /tmp/hosts
      register: catstdout

    - debug: msg="{{ catstdout.stdout }}"
    - debug: msg="{{ catstdout.stderr }}"