- name: Ejemplo etiquetas
  hosts: curso03
  tasks:
    - debug:
        msg: Tarea con tag PROD
      tags: prod
      
    - debug:
        msg: Tarea con tag DEV
      tags: dev

    - debug:
        msg: Tarea con varios tags
      tags: [qa, prod]

# ansible-playbook --tags qa,dev etiquetas.yml

# ansible-playbook --skip-tags prod etiquetas.yml

    - debug:
        msg: Esta tarea se ejecuta siempre
      tags: always