# - name: Instalar apache2
#   include: instalar-apache2.yml

- name: Copiar fichero index.html
  template: src=index.html.j2 dest=/var/www/html/index.html
  register: copiado

- name: Mostrar contenido
  command: cat /var/www/html/index.html
  register: salida
  when: copiado.changed == true

- debug: 
    var: salida.stdout
  when: copiado.changed == true

- debug: 
    var: copiado.changed
  # when: copiado.changed == true

- name: Copiar fichero de configuracion
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify: restart_httpd


