- name: Playbook para la clase de register
  hosts: curso01
  tasks: 
    - name: Ejecutar comando uptime
      command: uptime
      register: salida_uptime
    - name: Visualizar variable
      debug: 
        var: salida_uptime
        # var: salida_uptime.stdout